# gem5 build submission file
universe = docker
docker_image = gcr.io/gem5-test/ubuntu-20.04_all-dependencies

log = r.log
error = r.err
output = r.out

executable = submit/run_gem5.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = repo/gem5-resources/src/parsec/

request_cpus = 4
request_memory = 8GB
request_disk = 12GB

notify_user = zhewen.pan@wisc.edu
notification = always

queue 1