# gem5 build submission file
universe = docker
docker_image = gcr.io/gem5-test/ubuntu-20.04_all-dependencies

log = log/run_base_$(Cluster)_$(Process).log
error = err/run_base_$(Cluster)_$(Process).err
output = out/run_base_$(Cluster)_$(Process).out

executable = submit/test.sh
# arguments = $(ProcId)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = repo/gem5-resources/src/parsec/

request_cpus = 4
request_memory = 64GB
request_disk = 64GB

notify_user = zhewen.pan@wisc.edu
notification = always

queue 1